---
- name: ec2 launcher
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    key_name: aws_key
    region: us-east-2
  
  tasks:
    - name: Create a new EC2 key
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
      register: ec2_key

    - name: Save private key
      copy: content="{{ ec2_key.key.private_key }}" dest="./{{ key_name }}.pem" mode=0600
      when: ec2_key.changed

    - name: launch dev instance
      ec2:
        instance_tags:
          Name: boxfuse-dev
        key_name: "{{ key_name }}"

    - name: Add new instances to host group
      add_host: hostname={{item.public_ip}} groupname=dev
      with_items: ec2.instances

    - name: Wait for the instances to boot by checking the ssh port
      wait_for: host={{item.public_dns_name}} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: Configure dev instance
  hosts: dev
  connection: ssh
  remote_user: ubuntu
  gather_facts: true

  vars:
    proj_dir: /var/lib/boxfuse-sample-java-war-hello
    ansible_ssh_user: "ubuntu"

  tasks:
    - name: ensure python, maven, jdk, git, docker.io installed
      become: true
      apt:
        name: ['default-jdk', 'maven', 'git', 'python3', 'docker.io']
        state: present
        update_cache: true
 
    - name: Ensure that project dir is empty
      file:
        path: "{{ proj_dir }}"
        state: absent

    - name: Clone project
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: "{{ proj_dir }}"

    - name: Build project
      shell: "mvn package -f {{ proj_dir }}/pom.xml"