---
- name: ec2 launcher
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    key_name: aws_key
    region: us-east-2
  
  tasks:
    - name: launch dev instance
      ec2_instance_info:
        filters:
          "tag:Name": boxfuse-dev
          instance-state-name: ['running']
      register: ec2

    - name: Add new instances to host group
      add_host: 
        hostname: "{{ item.public_ip_address }}" 
        groups: 
          - dev
        #key_name: aws_key
      loop: "{{ ec2.instances }}"

- name: Configure dev instance
  hosts: dev
  connection: ssh
  remote_user: ubuntu
  become: true
  gather_facts: true

  vars:
    proj_dir: /var/lib/boxfuse-sample-java-war-hello
    pub_key_path: "~/.ssh/id_rsa.pub"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_ssh_user: "ubuntu"

  tasks:
    - name: ensure python, maven, jdk, git, docker.io installed
      apt:
        name: ['default-jdk', 'maven', 'git', 'python3', 'docker.io']
        state: present
        update_cache: true
 
    - name: Ensure that project dir is empty
      file:
        path: "{{ proj_dir }}"
        state: absent

    - name: Clone project
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: "{{ proj_dir }}"

    - name: Build project
      shell: "mvn package -f {{ proj_dir }}/pom.xml"